import { recipes, ingredients, defaultPantry } from './data.js';
import { getAvailability, getIngredientAvailability } from './domain.js';
import { loadState, saveState } from './storage.js';
import { DEFAULT_STATE, addPantryItem, updatePantryItem, removePantryItem, addRecipeToPlan, addMissingIngredients, reconcilePlannedGroceries, addManualGroceryItem, toggleGroceryItem } from './state.js';
import { renderToday } from './screens/today.js';
import { renderPlan } from './screens/plan.js';
import { renderRecipes } from './screens/recipes.js';
import { renderPantry } from './screens/pantry.js';
import { renderGrocery } from './screens/grocery.js';
import { todayISO, ingredientById, label, recipeArt } from './ui.js';
let currentView = 'today'; let mood = 'quick'; let filters = { search: '', tag: '', stocked: false, time: '' }; let saveFailed = false;
const fallbackState = { ...DEFAULT_STATE, pantry: defaultPantry.map(item => ({ ...item })) }; let state = loadState(window.localStorage, fallbackState);
const app = document.querySelector('#app'), modalWrap = document.querySelector('#modal-wrap'), modalContent = document.querySelector('#modal-content'), toast = document.querySelector('#toast'), persistenceNotice = document.querySelector('#persistence-notice');
function persist(next) { state = next; saveFailed = !saveState(window.localStorage, state); render(); }
function dispatch(action) { try { persist(action(state)); } catch (error) { showToast(error.message); } }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 2400); }
function openModal(html) { modalContent.innerHTML = html; modalWrap.classList.add('open'); modalWrap.setAttribute('aria-hidden', 'false'); modalContent.querySelector('button, input')?.focus(); }
function closeModal() { modalWrap.classList.remove('open'); modalWrap.setAttribute('aria-hidden', 'true'); }
function recipeDetail(recipe, step = 0) {
  const availability = getAvailability(recipe, state.pantry);
  const ingredientRows = recipe.ingredients.map(ref => {
    const item = ingredientById(ingredients, ref.ingredientId);
    const status = getIngredientAvailability(ref, state.pantry);
    return '<div class="detail-ingredient ' + (status.available ? 'available' : 'missing') + '"><span>' + item.icon + '</span><strong>' + item.name + '</strong><b>' + ref.quantity + ' ' + ref.unit + '</b><em>' + (status.available ? 'Available' : 'Missing') + '</em></div>';
  }).join('');
  return '<div class="modal-art">' + recipeArt(recipe) + '</div><p class="eyebrow">' + label(recipe.mealType) + ' · ' + recipe.timeMinutes + ' min · ' + recipe.difficulty + '</p><h2 id="modal-title">' + recipe.name + '</h2><p class="local-name">' + recipe.localName + '</p><div class="detail-tags">' + recipe.dietaryTags.map(tag => '<span class="tag">' + label(tag) + '</span>').join('') + '</div><div class="detail-block"><h3>Ingredients <span>' + availability.availableCount + '/' + availability.totalCount + ' stocked</span></h3>' + ingredientRows + '</div><div class="cook-panel"><div><p class="eyebrow">Cooking mode</p><h3>Step ' + (step + 1) + ' of ' + recipe.steps.length + '</h3></div><p>' + recipe.steps[step] + '</p><div class="cook-actions">' + (step > 0 ? '<button class="secondary-button" data-action="cook-step" data-recipe-id="' + recipe.id + '" data-step="' + (step - 1) + '">Back</button>' : '') + (step < recipe.steps.length - 1 ? '<button class="primary-button" data-action="cook-step" data-recipe-id="' + recipe.id + '" data-step="' + (step + 1) + '">Next step</button>' : '<button class="primary-button" data-close-modal>Done cooking</button>') + '</div></div><button class="wide-action" data-action="add-recipe-plan" data-recipe-id="' + recipe.id + '">+ Add to plan</button>';
}
function openRecipe(id, step = 0) { const recipe = recipes.find(item => item.id === id); if (recipe) openModal(recipeDetail(recipe, step)); }
function quickAdd() { openModal(`<p class="eyebrow">Quick add</p><h2 id="modal-title">What’s on your shelf?</h2><p class="modal-copy">One tap is enough. You can add details later.</p><div class="quick-grid">${ingredients.filter(item => ['egg','tomato','cooked-rice','chicken-thigh','yellow-noodles','onion','garlic','cucumber'].includes(item.id)).map(item => `<button class="quick-item" data-action="add-pantry" data-ingredient-id="${item.id}"><span>${item.icon}</span><strong>${item.name}</strong><small>${item.localName}</small></button>`).join('')}</div>`); }
function pickPlanRecipe(date, mealType) { const existing = state.mealPlan.find(item => item.date === date && item.mealType === mealType); openModal(`<p class="eyebrow">${label(mealType)} · ${date}</p><h2 id="modal-title">${existing ? 'Replace this meal' : 'Pick a recipe'}</h2><div class="pick-list">${recipes.map(recipe => `<button class="pick-recipe" data-action="confirm-plan" data-recipe-id="${recipe.id}" data-date="${date}" data-meal-type="${mealType}"><span>&#127859;</span><strong>${recipe.name}</strong><small>${recipe.timeMinutes} min</small></button>`).join('')}</div>${existing ? '<button class="secondary-button remove-from-modal" data-action="remove-plan" data-date="'+date+'" data-meal-type="'+mealType+'">Remove meal</button>' : ''}`); }
function editPantry(id) { const item = state.pantry.find(entry => entry.id === id); if (!item) return; const expired = item.expiryDate && item.expiryDate < todayISO(); openModal(`<p class="eyebrow">Pantry details</p><h2 id="modal-title">${item.name || ingredientById(ingredients, item.ingredientId).name}</h2>${expired ? '<div class="expired-note"><strong>Past its best</strong><span>Keep it, remove it, or add a replacement.</span></div>' : ''}<label class="field-label" for="pantry-quantity">Quantity</label><input class="field-input" id="pantry-quantity" data-pantry-field="quantity" type="number" min="0" step="0.5" value="${item.quantity ?? 0}"><label class="field-label" for="pantry-expiry">Expiry date</label><input class="field-input" id="pantry-expiry" data-pantry-field="expiryDate" type="date" value="${item.expiryDate || ''}"><button class="primary-button wide-form-action" data-action="save-pantry" data-pantry-id="${id}">Save changes</button>${expired ? '<div class="expired-actions"><button class="secondary-button" data-action="keep-pantry">Keep</button><button class="secondary-button" data-action="replace-pantry">Add replacement</button><button class="secondary-button" data-action="remove-pantry" data-pantry-id="'+id+'">Remove</button></div>' : '<button class="text-button remove-pantry-link" data-action="remove-pantry" data-pantry-id="'+id+'">Remove from pantry</button>'}`); }
function render() { app.innerHTML = currentView === 'today' ? renderToday({ recipes, ingredients, state, mood }) : currentView === 'plan' ? renderPlan({ recipes, state }) : currentView === 'recipes' ? renderRecipes({ recipes, ingredients, state, filters }) : currentView === 'pantry' ? renderPantry({ recipes, ingredients, state }) : renderGrocery({ state }); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === currentView)); document.querySelector('#grocery-count').textContent = state.grocery.filter(item => !item.checked).length || ''; persistenceNotice.hidden = !saveFailed; }
function chooseView(view) { currentView = view; render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
document.addEventListener('click', event => { const view = event.target.closest('[data-view]')?.dataset.view; if (view) { event.preventDefault(); chooseView(view); return; } const target = event.target.closest('[data-action]'); if (!target) { if (event.target.closest('[data-close-modal]')) closeModal(); return; } const action = target.dataset.action;
 if (action === 'open-recipe') openRecipe(target.dataset.recipeId); if (action === 'open-pantry') chooseView('pantry'); if (action === 'quick-add') quickAdd(); if (action === 'set-mood') { mood = target.dataset.mood; render(); }
 if (action === 'add-pantry') { const ingredient = ingredients.find(item => item.id === target.dataset.ingredientId); dispatch(s => addPantryItem(s, { ingredientId: ingredient.id, name: ingredient.name, icon: ingredient.icon, quantity: ingredient.id === 'egg' ? 6 : 1, unit: ingredient.defaultUnit })); closeModal(); showToast(`${ingredient.name} added to pantry`); }
 if (action === 'add-recommendation') { const recipe = recipes.find(item => item.id === target.dataset.recipeId); pickPlanRecipe(todayISO(), recipe.mealType); } if (action === 'pick-plan-recipe') pickPlanRecipe(target.dataset.date, target.dataset.mealType);
 if (action === 'confirm-plan') { const recipe = recipes.find(item => item.id === target.dataset.recipeId); const availability = getAvailability(recipe, state.pantry); const missing = availability.missing.map(m => ({ ...m, id: `grocery-${m.ingredientId}-${m.unit}`, name: ingredientById(ingredients, m.ingredientId).name, category: ingredientById(ingredients, m.ingredientId).category, source: 'recipe' })); dispatch(s => reconcilePlannedGroceries(addRecipeToPlan(s, { date: target.dataset.date, mealType: target.dataset.mealType, recipeId: recipe.id }), recipes, ingredients)); closeModal(); showToast(`${recipe.name} added to your plan`); }
 if (action === 'add-recipe-plan') pickPlanRecipe(todayISO(), recipes.find(r => r.id === target.dataset.recipeId)?.mealType || 'dinner'); if (action === 'cook-step') openRecipe(target.dataset.recipeId, Number(target.dataset.step)); if (action === 'toggle-grocery') dispatch(s => toggleGroceryItem(s, target.dataset.groceryId));
 if (action === 'add-manual-grocery') {
  openModal('<p class="eyebrow">Add to your list</p><h2 id="modal-title">A little extra</h2><label class="field-label" for="manual-name">Item</label><input class="field-input" id="manual-name" data-manual-field="name" placeholder="e.g. Limes"><label class="field-label" for="manual-quantity">Quantity</label><input class="field-input" id="manual-quantity" data-manual-field="quantity" type="number" min="0.1" step="0.1" value="1"><label class="field-label" for="manual-unit">Unit</label><input class="field-input" id="manual-unit" data-manual-field="unit" value="pieces"><label class="field-label" for="manual-category">Category</label><input class="field-input" id="manual-category" data-manual-field="category" value="Kitchen"><button class="primary-button wide-form-action" data-action="save-manual-grocery">Add to grocery</button>');
}
if (action === 'save-manual-grocery') {
  const fields = Object.fromEntries([...modalContent.querySelectorAll('[data-manual-field]')].map(field => [field.dataset.manualField, field.value]));
  dispatch(s => addManualGroceryItem(s, fields)); closeModal(); showToast('Added to grocery');
}
if (action === 'clear-checked') { persist({ ...state, grocery: state.grocery.filter(item => !item.checked) }); showToast('Checked items cleared'); } if (action === 'remove-plan') { persist(reconcilePlannedGroceries({ ...state, mealPlan: state.mealPlan.filter(item => !(item.date === target.dataset.date && item.mealType === target.dataset.mealType)) }, recipes, ingredients)); closeModal(); showToast('Meal removed'); } if (action === 'edit-pantry') editPantry(target.dataset.pantryId); if (action === 'save-pantry') { const fields = Object.fromEntries([...modalContent.querySelectorAll('[data-pantry-field]')].map(field => [field.dataset.pantryField, field.value])); dispatch(s => updatePantryItem(s, target.dataset.pantryId, fields)); closeModal(); showToast('Pantry updated'); } if (action === 'remove-pantry') { dispatch(s => removePantryItem(s, target.dataset.pantryId)); closeModal(); showToast('Removed from pantry'); } if (action === 'keep-pantry') { closeModal(); showToast('Keeping it for now'); } if (action === 'replace-pantry') { closeModal(); quickAdd(); } if (event.target.closest('[data-close-modal]')) closeModal(); });
document.addEventListener('input', event => { if (event.target.matches('[data-filter="search"]')) { filters.search = event.target.value; render(); const input = document.querySelector('[data-filter="search"]'); input?.focus(); input?.setSelectionRange(filters.search.length, filters.search.length); } });
document.addEventListener('click', event => { const tag = event.target.closest('[data-filter-tag]'); if (tag) { filters.tag = tag.dataset.filterTag; filters.stocked = false; render(); } const stocked = event.target.closest('[data-filter-stocked]'); if (stocked) { filters.stocked = !filters.stocked; render(); } const time = event.target.closest('[data-filter-time]'); if (time) { filters.time = time.dataset.filterTime; render(); } });
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(); const roleButton = event.target.closest('[role="button"]'); if ((event.key === 'Enter' || event.key === ' ') && roleButton) { event.preventDefault(); roleButton.click(); } });
window.addEventListener('beforeunload', () => saveState(window.localStorage, state)); render();