import { recipes, ingredients, defaultPantry } from './data.js';
import { getAvailability, getExpiryRecommendations } from './domain.js';
import { loadState, saveState } from './storage.js';
import { DEFAULT_STATE, addPantryItem, addRecipeToPlan, addMissingIngredients, toggleGroceryItem } from './state.js';
import { renderToday } from './screens/today.js';
import { renderPlan } from './screens/plan.js';
import { renderRecipes } from './screens/recipes.js';
import { renderPantry } from './screens/pantry.js';
import { renderGrocery } from './screens/grocery.js';
import { todayISO, ingredientById, label, recipeArt } from './ui.js';

let currentView = 'today';
let filters = { search: '', tag: '', stocked: false };
const fallbackState = { ...DEFAULT_STATE, pantry: defaultPantry.map(item => ({ ...item })) };
let state = loadState(window.localStorage, fallbackState);
const app = document.querySelector('#app');
const modalWrap = document.querySelector('#modal-wrap');
const modalContent = document.querySelector('#modal-content');
const toast = document.querySelector('#toast');

function persist(next) { state = next; saveState(window.localStorage, state); render(); }
function dispatch(action) { try { persist(action(state)); } catch (error) { showToast(error.message); } }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 2200); }
function openModal(html) { modalContent.innerHTML = html; modalWrap.classList.add('open'); modalWrap.setAttribute('aria-hidden', 'false'); modalContent.querySelector('button, input')?.focus(); }
function closeModal() { modalWrap.classList.remove('open'); modalWrap.setAttribute('aria-hidden', 'true'); }
function recipeDetail(recipe, step = 0) { const availability = getAvailability(recipe, state.pantry); return `<div class="modal-art">${recipeArt(recipe)}</div><p class="eyebrow">${label(recipe.mealType)} · ${recipe.timeMinutes} min · ${recipe.difficulty}</p><h2 id="modal-title">${recipe.name}</h2><p class="local-name">${recipe.localName}</p><div class="detail-tags">${recipe.dietaryTags.map(tag => `<span class="tag">${label(tag)}</span>`).join('')}</div><div class="detail-block"><h3>Ingredients <span>${availability.availableCount}/${availability.totalCount} stocked</span></h3><div class="detail-ingredients">${recipe.ingredients.map(ref => { const item = ingredientById(ingredients, ref.ingredientId); const available = !availability.missing.some(m => m.ingredientId === ref.ingredientId); return `<div class="detail-ingredient ${available ? 'available' : 'missing'}"><span>${item.icon}</span><strong>${item.name}</strong><b>${ref.quantity} ${ref.unit}</b></div>`; }).join('')}</div></div><div class="cook-panel"><div><p class="eyebrow">Cooking mode</p><h3>Step ${step + 1} of ${recipe.steps.length}</h3></div><p>${recipe.steps[step]}</p><div class="cook-actions">${step > 0 ? `<button class="secondary-button" data-action="cook-step" data-recipe-id="${recipe.id}" data-step="${step - 1}">Back</button>` : ''}${step < recipe.steps.length - 1 ? `<button class="primary-button" data-action="cook-step" data-recipe-id="${recipe.id}" data-step="${step + 1}">Next step</button>` : '<button class="primary-button" data-close-modal>Done cooking</button>'}</div></div><button class="wide-action" data-action="add-recipe-plan" data-recipe-id="${recipe.id}">＋ Add to plan</button>`; }
function openRecipe(id, step = 0) { const recipe = recipes.find(item => item.id === id); if (recipe) openModal(recipeDetail(recipe, step)); }
function quickAdd() { openModal(`<p class="eyebrow">Quick add</p><h2 id="modal-title">What’s on your shelf?</h2><p class="modal-copy">One tap is enough. You can add details later.</p><div class="quick-grid">${ingredients.filter(item => ['egg', 'tomato', 'cooked-rice', 'chicken-thigh', 'yellow-noodles', 'onion', 'garlic', 'cucumber'].includes(item.id)).map(item => `<button class="quick-item" data-action="add-pantry" data-ingredient-id="${item.id}"><span>${item.icon}</span><strong>${item.name}</strong><small>${item.localName}</small></button>`).join('')}</div>`); }
function pickPlanRecipe(date, mealType) { openModal(`<p class="eyebrow">${label(mealType)} · ${date}</p><h2 id="modal-title">Pick a recipe</h2><div class="pick-list">${recipes.map(recipe => `<button class="pick-recipe" data-action="confirm-plan" data-recipe-id="${recipe.id}" data-date="${date}" data-meal-type="${mealType}"><span>${recipe.id.includes('mee') ? '🍜' : '🍛'}</span><strong>${recipe.name}</strong><small>${recipe.timeMinutes} min</small></button>`).join('')}</div>`); }
function render() { const props = { recipes, ingredients, state, filters }; app.innerHTML = currentView === 'today' ? renderToday(props) : currentView === 'plan' ? renderPlan(props) : currentView === 'recipes' ? renderRecipes(props) : currentView === 'pantry' ? renderPantry(props) : renderGrocery(props); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === currentView)); const unchecked = state.grocery.filter(item => !item.checked).length; document.querySelector('#grocery-count').textContent = unchecked || ''; }
function chooseView(view) { currentView = view; render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }

document.addEventListener('click', event => { const view = event.target.closest('[data-view]')?.dataset.view; if (view) { event.preventDefault(); chooseView(view); return; } const target = event.target.closest('[data-action]'); if (!target) { if (event.target.closest('[data-close-modal]')) closeModal(); return; } const action = target.dataset.action; if (action === 'open-recipe') openRecipe(target.dataset.recipeId); if (action === 'open-pantry') chooseView('pantry'); if (action === 'quick-add') quickAdd(); if (action === 'add-pantry') { const ingredient = ingredients.find(item => item.id === target.dataset.ingredientId); dispatch(s => addPantryItem(s, { ingredientId: ingredient.id, name: ingredient.name, icon: ingredient.icon, quantity: ingredient.id === 'egg' ? 6 : 1, unit: ingredient.defaultUnit })); closeModal(); showToast(`${ingredient.name} added to pantry`); } if (action === 'add-recommendation') { const recipe = recipes.find(item => item.id === target.dataset.recipeId); pickPlanRecipe(todayISO(), recipe.mealType); } if (action === 'pick-plan-recipe') pickPlanRecipe(target.dataset.date, target.dataset.mealType); if (action === 'confirm-plan') { const recipe = recipes.find(item => item.id === target.dataset.recipeId); const availability = getAvailability(recipe, state.pantry); dispatch(s => addMissingIngredients(addRecipeToPlan(s, { date: target.dataset.date, mealType: target.dataset.mealType, recipeId: recipe.id }), availability.missing.map(m => ({ ...m, name: ingredientById(ingredients, m.ingredientId).name, category: ingredientById(ingredients, m.ingredientId).category, source: 'recipe' })))); closeModal(); showToast(`${recipe.name} added to your plan`); } if (action === 'add-recipe-plan') { pickPlanRecipe(todayISO(), recipes.find(r => r.id === target.dataset.recipeId)?.mealType || 'dinner'); } if (action === 'cook-step') openRecipe(target.dataset.recipeId, Number(target.dataset.step)); if (action === 'toggle-grocery') dispatch(s => toggleGroceryItem(s, target.dataset.groceryId)); if (action === 'clear-checked') { persist({ ...state, grocery: state.grocery.filter(item => !item.checked) }); showToast('Checked items cleared'); } if (event.target.closest('[data-close-modal]')) closeModal(); });
document.addEventListener('input', event => { if (event.target.matches('[data-filter="search"]')) { filters.search = event.target.value; render(); const input = document.querySelector('[data-filter="search"]'); input?.focus(); input?.setSelectionRange(filters.search.length, filters.search.length); } });
document.addEventListener('click', event => { const tag = event.target.closest('[data-filter-tag]'); if (tag) { filters.tag = tag.dataset.filterTag; filters.stocked = false; render(); } const stocked = event.target.closest('[data-filter-stocked]'); if (stocked) { filters.stocked = !filters.stocked; render(); } });
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(); if (event.key === 'Enter' && event.target.matches('[role="button"]')) event.target.click(); });
window.addEventListener('beforeunload', () => saveState(window.localStorage, state));
render();
