const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
export const label = value => String(value).replace(/-/g, ' ').replace(/\b\w/g, char => char.toUpperCase());
export const formatDate = value => new Intl.DateTimeFormat('en-MY', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(`${value}T12:00:00`));
export const todayISO = () => new Date().toISOString().slice(0, 10);
const recipeEmoji = recipe => recipe.id.includes('mee') ? '🍜' : recipe.id.includes('porridge') ? '🥣' : recipe.id.includes('roti') ? '🫓' : recipe.id.includes('chicken') ? '🍗' : '🍳';
export const recipeArt = recipe => `<div class="food-art ${esc(recipe.id)}" role="img" aria-label="Illustration of ${esc(recipe.name)}"><img class="food-photo" src="${esc(recipe.image)}" alt="" loading="lazy" onload="this.classList.add('loaded')" onerror="this.onerror=null; this.src='${esc(recipe.fallbackImage)}'; this.classList.add('loaded')"><span class="food-fallback" aria-hidden="true"><span class="food-emoji">${recipeEmoji(recipe)}</span><span class="art-spark">✦</span></span></div>`;
export function recipeCard(recipe, availability, action = 'open-recipe') { return `<article class="recipe-card" data-action="${action}" data-recipe-id="${esc(recipe.id)}" tabindex="0" role="button">${recipeArt(recipe)}<div class="recipe-info"><div class="card-kicker">${label(recipe.mealType)} · ${recipe.difficulty}</div><h3>${esc(recipe.name)}</h3><div class="recipe-meta"><span>⏱ ${recipe.timeMinutes} min</span><span class="dot"></span><span>${availability ? `${availability.availableCount}/${availability.totalCount} stocked` : ''}</span></div><div class="tag-row">${recipe.dietaryTags.slice(0, 2).map(tag => `<span class="tag">${label(tag)}</span>`).join('')}</div></div></article>`; }
export const emptyState = (title, copy, action, actionLabel) => `<div class="empty-state"><span class="empty-emoji">🥄</span><h2>${title}</h2><p>${copy}</p>${action ? `<button class="primary-button" data-action="${action}">${actionLabel}</button>` : ''}</div>`;
export const ingredientById = (ingredients, id) => ingredients.find(item => item.id === id) ?? { name: id, icon: '•', category: 'Other', defaultUnit: 'pieces' };
